import type { Metadata } from "next";
import "./globals.css";
import { Inter, Cherry_Bomb_One } from "next/font/google";
import { ThemeProvider } from "next-themes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const cherryBombOne = Cherry_Bomb_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cherry-bomb",
  display: "swap"
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${cherryBombOne.variable}`}>
      <body className="min-h-screen">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ThemeProvider>
            <main>{children}</main>
          </ThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
