import React from "react";
import Header from "./components/Header";
import Userfrontfield from "./UserFrontPage/Userfrontfield";
import type { Metadata, Viewport } from "next";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Apache PMS - Hotel Booking App",
  description: "Generated by create next app"
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};
export default function Home() {
  return (
    <div className="">
      <header>
        <Header />
      </header>
      <main>
        <Userfrontfield />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
