import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
          <ThemeProvider>
            <main>{children}</main>
          </ThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
